#
###################################
# Site wide configuration
####################################
#
title: Matt Blogsordo
email: mattdelsordo@gmail.com
description: Matt DelSordo's Good Blog
url: https://blog.mattdelsordo.com
keywords: ["matt", "delsordo"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          New York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Matt DelSordo
  avatar: avatar.jpg
  job: "Software Developer, Amateur Musician, Etc."
  bio: "I like to enjoy things and also talk about why I enjoy (or sometimes don't enjoy) those things. This blog is like the podcast \"Wonderful\", but just me. You can also find links to projects that I've released out into the wild along with posts about those projects if I ever update them or release new stuff."
  email: mattdelsordo@gmail.com
  # disqus-shortname:
  # twitter: #username
  # facebook: #username
  # google:
  #   plus: #username
  #   analytics:
  #   verify:
  #   ad-client:
  #   ad-slot:
  # bing-verify:
  github: mattdelsordo
  # gitlab: #username
  # stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: mattdelsordo
  # skype: #username
  # xing: #username
  # instagram: #username
  # lastfm: #username
  # tumblr: #username
  # pinterest: #username
  # foursquare: #username
  # steam: #username
  # dribbble: #username
  # youtube: #username
  # soundcloud: #username
  # weibo: #username
  # flickr: #username
  # 500px: #username
  # codepen: #username
  # reddit: #username
  # telegram: #username
